In [3]:
import pandas as pd

In [4]:
df = pd.read_csv("data.csv")

In [5]:
df

Fever  bodyPain  Age  runningNose  diffBreath  infectionProb
0      98.321993         1   53            0           0              0
1      98.209030         0   52            0           0              0
2     100.833942         1   68            0           0              1
3      99.184825         1   41            1           0              1
4     101.537503         1   49            0           0              0
...          ...       ...  ...          ...         ...            ...
3994   98.654896         1   36            0           1              1
3995   99.164527         0   38            0           0              0
3996   99.602035         1   61            0          -1              0
3997  100.062859         1   97            0          -1              0
3998   99.175251         0   77            0          -1              0

[3999 rows x 6 columns]

In [6]:
df.head()

Fever  bodyPain  Age  runningNose  diffBreath  infectionProb
0   98.321993         1   53            0           0              0
1   98.209030         0   52            0           0              0
2  100.833942         1   68            0           0              1
3   99.184825         1   41            1           0              1
4  101.537503         1   49            0           0              0

In [7]:
df.tail()

Fever  bodyPain  Age  runningNose  diffBreath  infectionProb
3994   98.654896         1   36            0           1              1
3995   99.164527         0   38            0           0              0
3996   99.602035         1   61            0          -1              0
3997  100.062859         1   97            0          -1              0
3998   99.175251         0   77            0          -1              0

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3999 entries, 0 to 3998
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Fever          3999 non-null   float64
 1   bodyPain       3999 non-null   int64  
 2   Age            3999 non-null   int64  
 3   runningNose    3999 non-null   int64  
 4   diffBreath     3999 non-null   int64  
 5   infectionProb  3999 non-null   int64  
dtypes: float64(1), int64(5)
memory usage: 187.6 KB


In [9]:
df.describe()

Fever     bodyPain          Age  runningNose   diffBreath  \
count  3999.000000  3999.000000  3999.000000  3999.000000  3999.000000   
mean    100.009418     0.503626    50.758440     0.496624     0.002501   
std       1.147553     0.500049    28.861378     0.500051     0.805492   
min      98.001883     0.000000     1.000000     0.000000    -1.000000   
25%      99.036292     0.000000    25.000000     0.000000    -1.000000   
50%     100.012980     1.000000    51.000000     0.000000     0.000000   
75%     101.006477     1.000000    76.000000     1.000000     1.000000   
max     101.999759     1.000000   100.000000     1.000000     1.000000   

       infectionProb  
count    3999.000000  
mean        0.507127  
std         0.500012  
min         0.000000  
25%         0.000000  
50%         1.000000  
75%         1.000000  
max         1.000000

In [10]:
df['infectionProb'].value_counts()

1    2028
0    1971
Name: infectionProb, dtype: int64

In [11]:
import numpy as np

In [12]:
def data_split(data, ratio):
    np.random.seed(42)
    shuffled = np.random.permutation(len(data))
    test_set_size = int(len(data) * ratio)
    test_indeces = shuffled[:test_set_size]
    train_indeces = shuffled[test_set_size:]
    return data.iloc[train_indeces], data.iloc[test_indeces]

In [13]:
np.random.permutation(7)

array([0, 2, 4, 1, 6, 5, 3])

In [14]:
train, test = data_split(df, 0.2)

In [15]:
train

Fever  bodyPain  Age  runningNose  diffBreath  infectionProb
2990   99.373352         0   17            0          -1              1
1575   99.963039         1   49            1          -1              1
506    99.758374         1   16            1           0              0
3593  101.073676         1   63            0          -1              0
3562   98.062316         0   79            1          -1              0
...          ...       ...  ...          ...         ...            ...
1130  100.469410         1   40            1           1              1
1294  100.180215         0   46            0           1              1
860   101.973553         0   72            0           1              0
3507   99.025454         1   40            1           0              1
3174  101.751568         1    6            0          -1              0

[3200 rows x 6 columns]

In [16]:
test

Fever  bodyPain  Age  runningNose  diffBreath  infectionProb
1760   98.878146         0   12            1           0              1
3326   99.093910         0   59            1          -1              1
1770   99.110577         0    6            0          -1              0
3176  101.267342         1   85            0          -1              1
2099  101.444049         1   76            1           1              1
...          ...       ...  ...          ...         ...            ...
1602   99.490552         1    8            1           0              0
2510   98.247657         0   71            0          -1              1
2752  100.327322         1   88            0           1              1
1869  101.137444         1   60            0           1              1
423    99.477315         1    4            0          -1              1

[799 rows x 6 columns]

In [17]:
X_train = train[['Fever', 'bodyPain', 'Age', 'runningNose', 'diffBreath']].to_numpy()
X_test = test[['Fever', 'bodyPain', 'Age', 'runningNose', 'diffBreath']].to_numpy()

In [19]:
y_train = train[['infectionProb']].to_numpy().reshape(3200,)
y_test = test[['infectionProb']].to_numpy().reshape(799,)

In [20]:
y_train

array([1, 1, 0, ..., 0, 1, 0], dtype=int64)

In [21]:
from sklearn.linear_model import LogisticRegression

In [22]:
clf = LogisticRegression()
clf.fit(X_train, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [26]:
inputFeatures = [99.110577, 1, 31, 1, 0]
clf.predict([inputFeatures])

array([1], dtype=int64)

In [32]:
clf.predict_proba([[99.110577, 0, 21, -1, 1]])

array([[0.49497965, 0.50502035]])

In [33]:
        infProb = clf.predict_proba([inputFeatures])[0][1]

In [34]:
infProb

0.5189243742367478